### ISSUE TITLE
Duplicate Thing for http-on-off-adapter

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/http-on-off-adapter#6]
With `http-on-off-adapter` release 0.3.3, the menu **Things > +** shows two devices, `LED` and `LED-F0277A`...

<img width="1268" alt="capture 2018-04-17 a 17 32 42" src="https://user-images.githubusercontent.com/951776/38880353-c508ae9c-4265-11e8-9775-1661bd92a7ba.png">

...with `http-on-off-adapter` being configured with `wifi101-F0277A.local`.

```
$ ./config-editor.py http-on-off-adapter
{
  "url": "http://wifi101-F0277A.local"
}
```

Both coexist on the dashboard, but are not synchronised.

<img width="1268" alt="capture 2018-04-17 a 17 37 04" src="https://user-images.githubusercontent.com/951776/38880438-080246fe-4266-11e8-8610-219fb3966989.png">

**Comment by dhylands** [comment]
The one called LED is typically tied to http://wifi101.local whereas LED-F0277A is tied to https://wifi101-F0277A.local
It used to be configured by default, but once we added mDNS discovery we don't configure it by default any more.

**Comment by rei-vilo** [comment]
Thanks!
